### ISSUE TITLE
Project discontinued? 

### ISSUE THREAD

**Issue by Roms1383** [DottieDot/ScriptHookV-rs#1]
Hi, sorry to open an issue for this but there's no Discussion tab for this kind of question : I've been following your progresses on this repo probably for the last 2 years but haven't had a chance to get into it (being mostly busy with developing mods for Cyberpunk 2077 so far).

Long message short: "are you discontinuing developments on this repository?"

p.s: also to be completely transparent, I'm mostly interested in RDR2, but your sourcecode clearly has the potential to support both GTA5 and RDR2 with some more work.

**Comment by DottieDot** [comment]
I currently don't have the time nor the motivation to continue on it. I do have some ambitions to revive it for GTA6, but realistically, that probably won't happen. There are also a few issues with the soundness of some of the code, for example the wrapper struct functions are not `unsafe`, even though calling them from the wrong thread would be bad. I do have a private repo that reworked certain aspects, but I can't remember the exact state of it...

**Comment by Roms1383** [comment]
Thanks for your reply, I utterly understand.
Would you mind keeping in touch? In case I finally decide to dive into the rabbit hole at some point, I'd like to have the opportunity to ask your feedback once in a while, so here's my Discord : roms1383.
